channels:
  - conda-forge
dependencies:
  - aimsgb =0.1.0
  - ase =3.22.0
  - coveralls
  - coverage
  - codacy-coverage
  - defusedxml =0.7.1
  - matplotlib-base =3.4.2
  - mendeleev =0.7.0
  - phonopy =2.11.0
  - pyiron_base =0.2.18
  - pymatgen =2022.0.10
  - pyscal =2.10.12
  - scipy =1.7.0
  - seekpath =2.0.1
  - six =1.16.0
  - scikit-learn =0.24.2
  - spglib =1.16.1
  - codacy-coverage
  - dill =0.3.4
  - future =0.18.2
  - gitpython =3.1.18
  - h5io =0.1.2
  - h5py =3.3.0
  - numpy =1.21.0
  - pandas =1.2.5
  - pathlib2 =2.3.5
  - psutil =5.8.0
  - pyfileindex =0.0.6
  - pysqa =0.0.15
  - pytables =3.6.1
  - sqlalchemy =1.4.19
  - tqdm =4.61.1
